version: '3.8'

services:
  yt-video-to-txt:
    build:
      context: .
      dockerfile: Dockerfile
    image: yt-video-to-txt:latest
    container_name: yt-video-to-txt
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - TEMP_DIR=/app/temp
      - OUTPUT_DIR=/app/output
      - LOGS_DIR=/app/logs
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./temp:/app/temp
    command: ["--help"]
    restart: "no"
    mem_limit: 2g
    cpus: 1.5

  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: yt-video-to-txt:dev
    container_name: yt-video-to-txt-dev
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/node_modules
    command: ["pnpm", "run", "dev"]
    restart: "no"
    stdin_open: true
    tty: true